version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: rate-limiter-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  fluentd:
    image: fluent/fluentd:v1.14-1
    container_name: rate-limiter-logs
    restart: always
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf

volumes:
  redis_data:
