version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - RATE_LIMIT=5
      - BLOCK_DURATION=60
    env_file:
      - cmd/.env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
