services:
  redis:
    image: redis:7.0
    container_name: redis_rate_limiter
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rate_limiter_network

  rate-limiter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate_limiter_app
    depends_on:
      - redis
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - rate_limiter_network

networks:
  rate_limiter_network:
    driver: bridge
